name: sms_project
description: A new Flutter project.

publish_to:

version: 1.0.0+9

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  native_auth: ^1.0.6
  flutter_sms_inbox: ^1.0.2
  fl_chart: ^0.61.0
  bottom_navy_bar: ^6.0.0
  device_info_plus: ^8.2.0
  http: ^0.13.5
  dio: ^5.0.3
  connectivity_plus: ^3.0.4
  permission_handler: ^10.2.0
  tutorial_coach_mark: ^1.2.8
  url_launcher: ^6.1.14
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_logo.png"

flutter:
  uses-material-design: true

  assets:
   - assets/images/


#  fonts:
#    - family: IranSBold
#      fonts:
#        - asset: assets/fonts/IRANSansXFaNum-Bold.ttf